# Generated by Django 4.1.7 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='specifications',
            field=models.TextField(),
        ),
    ]
