# Generated by Django 4.2.3 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='battery',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='connection',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='cruising_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='flight_radius',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='maximum_flight_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='maximum_take_off_weight',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
