# Generated by Django 4.2.3 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_drone_battery_drone_connection_drone_cruising_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='field_of_view',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='focal_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='iso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='size_of_the_image_sensor',
            field=models.IntegerField(null=True),
        ),
    ]
