# Generated by Django 4.2.3 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_drone_field_of_view_drone_focal_length_drone_iso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='iso',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
