# Generated by Django 4.2.3 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_drone_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='size_of_the_image_sensor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
